
export default class CommonStants {
  static readonly INPUt_ACCOUNT_LENGTH = 11;

  static readonly INPUT_PASSWORD_LENGTH = 8;

  static readonly INPUT_PADDING_LEFT = 0;

  static readonly COMMON_SPACE = 12;

  static readonly HOME_TITLE = 'Home';

  static readonly MINE_TITLE = 'My';

  static readonly LOGIN_METHODS_SPACE = 44;

  static readonly FULL_PARENT = '100%';

  static readonly BUTTON_WIDTH = '90%';

  static readonly HOME_TAB_INDEX = 0;

  static readonly MINE_TAB_INDEX = 1;
}